### ISSUE TITLE
Solventar: WARNING: No t_error rule is defined

### ISSUE THREAD

**Issue by ericknavarro** [RafaelCobar/OLC2BM_201700319_tareas_clase#1]
![image](https://user-images.githubusercontent.com/20389251/91922199-96ed5680-ec8a-11ea-8894-16fbcfdc4f9f.png)

**Comment by RafaelCobar** [comment]
Se arreglo el mensaje de error. 
Se debia de agregar la expresion regular para tokens desconocidos
